---
experiment:
  name: test

task_kwargs:
  # use_pixels: True
  # use_segment: True
  phantom: "low_tort"
  target: "bca"


wrapper_kwargs:
  use_obs:
    # - 'pixels'
    # - 'guidewire'
    - 'joint_pos'
    - 'joint_vel'





